# Generated by Django 4.2.5 on 2023-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_name", models.CharField(max_length=100)),
                ("stu_email", models.EmailField(max_length=254)),
                ("stu_city", models.CharField(max_length=50)),
            ],
        ),
    ]
