# Generated by Django 4.2.5 on 2023-09-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "get_latest_by": "order_date",
                "ordering": [-1],
                "verbose_name_plural": "Student",
            },
        ),
        migrations.AlterModelTable(
            name="student",
            table="stu_table",
        ),
    ]
