# Generated by Django 4.2.5 on 2023-09-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_student_options_alter_student_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tec_name", models.CharField(max_length=100)),
                ("tec_email", models.EmailField(max_length=254)),
                ("tec_city", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Teacher",
                "db_table": "tec_table",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name_plural": "Student"},
        ),
    ]
