# Generated by Django 4.2.5 on 2023-09-13 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_teacher_alter_student_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="tec_city",
            new_name="stu_city",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="tec_email",
            new_name="stu_email",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="tec_name",
            new_name="stu_name",
        ),
    ]
